Repository arawa/workspace, pull requests merged in 2022-09, with the labels that each got.

#557 Chore/update screenshots
  README.md
  appinfo/info.xml
  screenshots/workspace-add-users.png
  screenshots/workspace-details.png
  screenshots/workspace-home-small.png
  screenshots/workspace-home.png
  screenshots/workspace-subgroups.png
Labels: chore

#558 Chore/fix screenshot
  screenshots/workspace-details.png
  screenshots/workspace-home.png
  screenshots/workspace-subgroups.png
Labels: chore

#541 Add Czech localization - js.variant
  l10n/cs.js
Labels: translating

#542 Add Czech localization - .json variant
  l10n/cs.json
Labels: translating

#567 chore(): Update the CHANGELOG.md
  CHANGELOG.md
Labels: translating

#571 chore(): Change the summary
  appinfo/info.xml
Labels: chore, build
