Repository arawa/workspace, pull requests merged in 2023-03, with the labels that each got.

#742 chore(): Update comments about the new release GF
  README.md
  appinfo/info.xml
Labels: chore

#743 Backport: Update comments about the new release GF
  README.md
  appinfo/info.xml
Labels: chore, backport

#745 chore(controller): remove @NoCSRFRequired tokens
  CHANGELOG.md
  lib/Controller/GroupController.php
  lib/Controller/SpaceController.php
  lib/Controller/WorkspaceController.php
Labels: backend, chore

#748 Add release 2.0.0
  CHANGELOG.md
Labels: chore

#749 Move one line changelog
  CHANGELOG.md
Labels: chore

#750 Backport/remove no csrf required tokens/745/stable24
  CHANGELOG.md
  lib/Controller/GroupController.php
  lib/Controller/SpaceController.php
  lib/Controller/WorkspaceController.php
Labels: backend, chore, backport

#752 Update the release for stable24 to v1.3.3
  CHANGELOG.md
  appinfo/info.xml
Labels: chore

#751 Update the release for stable25 to v2.0.1
  CHANGELOG.md
  appinfo/info.xml
Labels: chore

#765 build(CI): Init Semgrep for the Workspace app
  .github/workflows/semgrep.yml
Labels: build

#767 Backport/add-semgrep-to-the-project/765/stable24
  .github/workflows/semgrep.yml
Labels: build, backport

#768 Backport/add-semgrep-to-the-project/765/stable25
  .github/workflows/semgrep.yml
Labels: build, backport
