Repository arawa/workspace, pull requests merged in 2023-05, with the labels that each got.

#794 Remove the space id in the title
  src/SpaceDetails.vue
Labels: frontend, refactor

#798 replace vue-notification by @nextcloud/dialogs
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  package-lock.json
  package.json
  src/Home.vue
  src/SelectUsers.vue
  src/SpaceDetails.vue
  src/main.js
  src/services/Notifications/NotificationError.js
  src/services/groupfoldersService.js
  src/services/spaceService.js
  src/store/actions.js
  src/tests/unit/groupfoldersService.test.js
  src/tests/unit/home.test.js
Labels: frontend, refactor

#806 chore(): Update the Changelog
  CHANGELOG.md
Labels: chore

#807 build(CI): add lint-eslint.yml file
  .github/workflows/lint-eslint.yml
  src/Errors/Groupfolders/AddGroupToGroupfolderError.js
  src/Errors/Groupfolders/EnableAclGroupfolderError.js
  src/Home.vue
  src/main.js
  src/router.js
  src/services/Notifications/NotificationError.js
  src/services/groupfoldersService.js
  src/services/spaceService.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/tests/__mocks__/axios.js
  src/tests/jest.setup.js
  src/tests/unit/groupfoldersService.test.js
  src/tests/unit/selectUsers.test.js
  src/tests/unit/store.test.js
Labels: build

#808 Change the translation in workspace
  l10n/cs.js
  l10n/cs.json
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  src/RemoveSpace.vue
Labels: frontend, chore

#814 Add 5s to notifications in a few places
  src/Home.vue
  src/services/groupfoldersService.js
  src/services/spaceService.js
  src/store/actions.js
Labels: frontend

#815 Backport/del space ncmodal/774/stable25
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  src/RemoveSpace.vue
  src/SpaceDetails.vue
Labels: frontend, backport

#816 backport/change-message-remove-wsp/808/stable25
  l10n/cs.js
  l10n/cs.json
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
Labels: frontend, backport

#797 Change php required to 8.2
  composer.json
  composer.lock
Labels: build

#796 Change fullclean command
  Makefile
Labels: build

#818 Refactor to be compatible with php8.0
  lib/Controller/GroupController.php
  lib/Controller/PageController.php
  lib/Controller/SpaceController.php
  lib/Controller/WorkspaceController.php
  lib/Db/Space.php
  lib/Db/SpaceMapper.php
  lib/Exceptions/BadRequestException.php
  lib/Middleware/IsGeneralManagerMiddleware.php
  lib/Middleware/IsSpaceAdminMiddleware.php
  lib/Middleware/WorkspaceAccessControlMiddleware.php
  lib/Migration/RegisterWorkspaceUsersGroup.php
  lib/Service/Group/GroupFormatter.php
  lib/Service/Group/GroupsWorkspaceService.php
  lib/Service/SpaceService.php
  lib/Service/User/UserFormatter.php
  lib/Service/User/UserWorkspace.php
  lib/Service/UserService.php
  lib/Service/Workspace/WorkspaceCheckService.php
  lib/Service/WorkspaceService.php
  tests/Integration/AppTest.php
  tests/Unit/Middleware/WorkspaceAccessControlMiddlewareTest.php
  tests/Unit/Service/UserServiceTest.php
Labels: backend, draft

#801 Fix/modal window hide
  src/SpaceDetails.vue
Labels: frontend, minor bug

#799 Fix/rename group
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  lib/Controller/GroupController.php
  lib/Exceptions/GroupException.php
  src/store/actions.js
Labels: backend, frontend, debug, draft

#827 Chore/update changelog
  CHANGELOG.md
Labels: chore

#828 chore(): Add new Changelog for dev
  docs/dev/CHANGELOG.md
Labels: chore

#829 chore(): New release 3.0.0
  CHANGELOG.md
  appinfo/info.xml
Labels: chore

#830 chore(): Update the CHANGELOG for dev
  docs/dev/CHANGELOG.md
Labels: chore

#831 chore(): NC25 is the min version for the v3.0.0
  appinfo/info.xml
Labels: chore

#834 Fix/update change groupsname
  appinfo/info.xml
  lib/Migration/ChangeGroupnamesV300.php
  lib/Migration/RegisterWorkspaceUsersGroup.php
Labels: backend, debug, important bug

#835 Hotfix/update change groupsname/834/stable3.0
  appinfo/info.xml
  lib/Migration/ChangeGroupnamesV300.php
  lib/Migration/RegisterWorkspaceUsersGroup.php
Labels: backend, debug, important bug

#836 chore(): Update the changelog and release 3.0.1
  CHANGELOG.md
  appinfo/info.xml
Labels: chore

#838 fix(vue): remove not used variable and replace by a proper one
  CHANGELOG.md
  docs/dev/CHANGELOG.md
  src/SpaceDetails.vue
Labels: frontend, important bug
