Repository arawa/workspace, pull requests merged in 2024-04, with the labels that each got.

#921 chore(): Merge changelogs with the stable3.0 changelog
  CHANGELOG.md
Labels: documentation

#802 From new core setting : use shareapi_only_share_with_group_members_ex…
  lib/Service/WorkspaceService.php
  lib/Share/Group/GroupMembersOnlyChecker.php
  lib/Share/Group/ShareMembersOnlyFilter.php
Labels: backend, draft

#953 backport: Limit the search to members
  lib/Service/WorkspaceService.php
  lib/Share/Group/GroupMembersOnlyChecker.php
  lib/Share/Group/ShareMembersOnlyFilter.php
Labels: backend, backport

#955 Release to 3.0.6
  appinfo/info.xml
Labels: release

#954 chore(): Update the changelog
  CHANGELOG.md
Labels: chore

#956 Chore/fix changelog
  CHANGELOG.md
  lib/Share/Group/ShareMembersOnlyFilter.php
Labels: chore

#957 fix(share): Remove git-diff in the ShareMembersOnlyFiler
  lib/Share/Group/ShareMembersOnlyFilter.php
Labels: debug, backport

#958 doc(info): Update of the user doc links
  appinfo/info.xml
Labels: documentation

#967 ci(php): Use php 8.1 and use stable28 and master
  .github/workflows/php.yml
Labels: ci
