Repository arawa/workspace, pull requests merged in 2025-02, with the labels that each got.

#1138 Remove upload-artifact as it is unsupported in GitHub Workflow v3
  .github/workflows/makefile.yml
Labels: build, ci

#1142 fix: 'exist' wording (is exist -> does exist)
  lib/Controller/GroupController.php
  lib/Controller/WorkspaceController.php
  lib/Group/Admin/AdminGroupManager.php
  lib/Group/User/UserGroupManager.php
  lib/Space/SpaceManager.php
  tests/Unit/Space/SpaceManagerTest.php
Labels: chore

#1129 Change "G.E." to "WM" in user role selection
  l10n/fr.js
  l10n/fr.json
Labels: translating

#1128 Update selecting user component
  src/MultiSelectUsers.vue
Labels: frontend, refactor

#1144 Backport: change select user component
  src/MultiSelectUsers.vue
Labels: frontend, refactor, backport

#1131 Hide disabled users from connected groups
  lib/Group/GroupBackend.php
  lib/Service/Group/GroupFormatter.php
  tests/Unit/Space/SpaceManagerTest.php
Labels: backend, debug

#1145 Backport: hide disabled users
  lib/Group/GroupBackend.php
  lib/Service/Group/GroupFormatter.php
  tests/Unit/Space/SpaceManagerTest.php
Labels: backend, debug, backport

#1123 Backport: Remove incompatibility groupfolders message
  README.md
Labels: documentation, backport

#1146 Backport: user counter when removing user
  lib/Controller/ConnectedGroupController.php
  lib/Service/Group/ConnectedGroupsService.php
  lib/Service/User/UserFormatter.php
  lib/Service/UserService.php
  lib/Users/UserFormatter.php
  tests/Unit/Service/UserServiceTest.php
Labels: backend, debug, refactor, backport

#1127 Backport: change image in readme
  README.md
Labels: documentation, backport

#1121 Harmonize hover effect for "Add a group" and "Create a workspace group" buttons
  src/SpaceMenuItem.vue
Labels: frontend, refactor

#1147 Backport: Harmonize hover effect for "Add a group" and "Create a workspace group" buttons
  src/SpaceMenuItem.vue
Labels: frontend, refactor, backport

#1148 Update release 4.0.1 dev1
  appinfo/info.xml
Labels: chore

#1153 Using the tab indent style for PHP, CSS, JS and Vue in our code editor
  .editorconfig
Labels: chore

#1154 fix: findAddedGroups is calling twice the same SQL query
  lib/Db/GroupFoldersGroupsMapper.php
Labels: backend, debug

#1160 Listing connected groups
  lib/Service/Group/ConnectedGroupsService.php
Labels: backend, debug

#1155 Load manager avatars in asynchronously with workspaces
  appinfo/routes.php
  lib/Controller/WorkspaceController.php
  package-lock.json
  package.json
  src/LeftSidebar.vue
  src/SpaceTable.vue
  src/WorkspaceContent.vue
  src/main.js
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
Labels: backend, frontend, debug

#1162 Translate error message for renaming a workspace
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  lib/Controller/WorkspaceController.php
  lib/Exceptions/AbstractNotification.php
  lib/Exceptions/BadRequestException.php
  lib/Exceptions/Notifications/AbstractNotificationException.php
  lib/Middleware/IsGeneralManagerMiddleware.php
  lib/Middleware/IsSpaceAdminMiddleware.php
  lib/Space/SpaceManager.php
  src/services/Notifications/NotificationError.js
  src/services/spaceService.js
Labels: backend, frontend, debug, refactor

#1164 Backport: translate rename space for stable4.0
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  lib/Controller/WorkspaceController.php
  lib/Exceptions/AbstractNotification.php
  lib/Exceptions/BadRequestException.php
  lib/Exceptions/Notifications/AbstractNotificationException.php
  lib/Middleware/IsGeneralManagerMiddleware.php
  lib/Middleware/IsSpaceAdminMiddleware.php
  lib/Space/SpaceManager.php
  src/services/Notifications/NotificationError.js
  src/services/spaceService.js
Labels: backend, frontend, debug, refactor, backport

#1150 Add user as workspace manager with workspace:create command, even if the workspace already exists
  lib/Commands/Create.php
  lib/Db/SpaceMapper.php
  lib/Space/SpaceManager.php
  tests/Unit/Space/SpaceManagerTest.php
Labels: backend, refactor

#1178 Backport: Users remnants show
  lib/Controller/ConnectedGroupController.php
  lib/Group/GroupBackend.php
  lib/Service/Group/GroupFormatter.php
Labels: backend, debug, backport

#1179 Release 4.0.1 rc1
  appinfo/info.xml
Labels: chore, release

#1180 Release 4.0.1
  CHANGELOG.md
  appinfo/info.xml
Labels: release

#1181 Update CHANGELOG for release 4.0.1
  CHANGELOG.md
Labels: documentation

#1183 Close file after analysis with correct comma usage
  lib/Files/Csv/SeparatorDetector.php
Labels: backend, debug

#1185 Backport: Close file after analysis with correct comma usage
  lib/Files/Csv/SeparatorDetector.php
Labels: backend, debug, backport

#1186 Update workspace to 4.0.2-rc1
  appinfo/info.xml
Labels: release

#1163 Backport: Load manager avatars in asynchronously with workspaces
  appinfo/routes.php
  lib/Controller/WorkspaceController.php
  package-lock.json
  package.json
  src/LeftSidebar.vue
  src/SpaceTable.vue
  src/WorkspaceContent.vue
  src/main.js
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
Labels: backend, frontend, debug, backport

#1187 Load users asynchronously when viewing a workspace
  src/SelectConnectedGroups.vue
  src/SpaceTable.vue
  src/UserCard.vue
  src/UserTable.vue
Labels: frontend, debug, refactor

#1188 Backport: Load users from users table view
  src/SelectConnectedGroups.vue
  src/SpaceTable.vue
  src/UserCard.vue
  src/UserTable.vue
Labels: frontend, debug, refactor, backport

#1192 Release 4.0.2-rc2
  appinfo/info.xml
Labels: chore, release

#1184 Reduce group search loading time
  lib/Controller/GroupController.php
  package-lock.json
  package.json
  src/SelectConnectedGroups.vue
Labels: backend, debug, major bug

#1193 Backport: Reduce group search loading time
  lib/Controller/GroupController.php
  package-lock.json
  package.json
  src/SelectConnectedGroups.vue
Labels: backend, debug, major bug, backport
