Repository arawa/workspace, pull requests merged in 2025-04, with the labels that each got.

#1228 Implement counter bubble for counting workspaces on the front-end
  appinfo/routes.php
  lib/Controller/WorkspaceController.php
  lib/Db/SpaceMapper.php
  src/LeftSidebar.vue
  src/WorkspaceContent.vue
  src/services/spaceService.js
Labels: backend, frontend, debug

#1229 Create a new modal window to edit a workspace
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  src/SpaceDetails.vue
  src/components/Modals/EditWorkspace.vue
Labels: feature, frontend

#1230 Revert "Release v4.1.0"
  appinfo/info.xml
Labels: revert, release

#1231 Ignore inconsistencies in the groups and subgroups listing for a workspace
  lib/Group/Admin/AdminUserGroup.php
  lib/Group/User/UserGroup.php
  lib/Service/Group/ConnectedGroupsService.php
  lib/Service/User/UserWorkspace.php
  lib/Service/UserService.php
  lib/Space/SpaceManager.php
Labels: backend, debug

#1232 Fix infinite loading problem in user list
  src/GroupDetails.vue
  src/SpaceDetails.vue
  src/WorkspaceContent.vue
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
Labels: frontend, debug

#1235 Backport: Ignore inconsistencies in the groups and subgroups listing for a workspace
  lib/Group/Admin/AdminUserGroup.php
  lib/Group/User/UserGroup.php
  lib/Service/Group/ConnectedGroupsService.php
  lib/Service/User/UserWorkspace.php
  lib/Service/UserService.php
  lib/Space/SpaceManager.php
Labels: backend, debug, backport

#1236 Backport: Fix infinite loading problem in user list
  src/GroupDetails.vue
  src/SpaceDetails.vue
  src/WorkspaceContent.vue
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
Labels: frontend, debug, backport

#1237 Release v4.0.3-rc1
  appinfo/info.xml
Labels: chore, release

#1239 Move set quota functionality to the new edit workspace modal
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  src/SpaceDetails.vue
  src/SpaceTable.vue
  src/WorkspaceContent.vue
  src/components/Modals/EditWorkspace.vue
  src/store/actions.js
  src/store/getters.js
Labels: feature, frontend

#1240 Reduce edit Workspace modal width
  src/components/Modals/EditWorkspace.vue
Labels: frontend

#1241 Remove makefile ci
  .github/workflows/makefile.yml
Labels: ci

#1244 Fixing typo and wording on warning log
  lib/Controller/WorkspaceController.php
  lib/Group/SubGroups/SubGroup.php
Labels: translating, chore

#1247 Backport: Fixing typo and wording on warning log
  lib/Controller/WorkspaceController.php
  lib/Group/SubGroups/SubGroup.php
Labels: translating, chore, backport

#1245 Remove duplicate conversion of quota string to bytes
  src/store/actions.js
Labels: frontend, debug

#1248 Backport: Remove all console.debug
  src/ButtonUploadShareFiles.vue
  src/GroupDetails.vue
  src/UserTable.vue
  src/store/actions.js
Labels: chore

#1238 Update fr.js for 2 error messages
  l10n/fr.js
Labels: translating

#1250 Backport: Update fr.js for 2 error messages
  l10n/fr.js
Labels: translating

#1251 Reduce the number of requests needed to get a user list
  src/MultiSelectUsers.vue
Labels: frontend, debug

#1249 Display acl inherit per user
  lib/AppInfo/Capabilities.php
  lib/Controller/PageController.php
  src/App.vue
  templates/index.php
  tests/Unit/Controller/PageControllerTest.php
Labels: feature

#1253 Update edit workspace modal to match original mockup
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  src/components/Modals/EditWorkspace.vue
  src/store/getters.js
Labels: frontend, debug, refactor

#1254 Fix the header for the group detail page
  css/workspace-style.css
  src/GroupDetails.vue
Labels: frontend, debug

#1255 Release v4.0.3-rc2
  appinfo/info.xml
Labels: chore, release

#1242 Crash of workspace list with undefined quota
  src/WorkspaceContent.vue
  src/store/getters.js
  src/tests/unit/workspaceContent.test.js
Labels: frontend, debug

#1256 Release v4.1.0-rc2
  appinfo/info.xml
Labels: chore, release

#1225 Backport: Optimize user state for users in added groups
  lib/Controller/ConnectedGroupController.php
  lib/Db/GroupFoldersGroupsMapper.php
  lib/Service/Group/ConnectedGroupsService.php
  lib/Service/User/UserFormatter.php
  lib/Service/UserService.php
  lib/Users/UserFormatter.php
Labels: backend, refactor, backport

#1258 Update release to v4.1.0-rc3
  appinfo/info.xml
Labels: chore, release

#1260 Remove duplicated users found from the backend
  src/MultiSelectUsers.vue
Labels: frontend, debug

#1262 Backport: Remove duplicated users
  src/MultiSelectUsers.vue
Labels: frontend, debug, backport

#1263 Release v4.0.3-rc3
  appinfo/info.xml
Labels: chore, release

#1259 Move setting of quota to backend
  appinfo/routes.php
  lib/Controller/WorkspaceController.php
  lib/Db/SpaceMapper.php
  src/store/actions.js
Labels: backend, frontend, api, refactor

#1264 Backport : move set quota backend
  appinfo/routes.php
  lib/Controller/WorkspaceController.php
  lib/Db/SpaceMapper.php
  src/store/actions.js
Labels: backend, frontend, api, refactor, backport

#1266 Release v4.0.3
  appinfo/info.xml
Labels: chore, release

#1267 Update CHANGELOG for v4.0.3
  CHANGELOG.md
Labels: documentation

#1268 Backport: Update CHANGELOG for v4.0.3
  CHANGELOG.md
Labels: documentation, backport

#1269 Fix infinite loading issue for users
  src/store/actions.js
  src/store/mutations.js
Labels: frontend, debug

#1270 Backport : Fix infinite loading issue for users
  src/store/actions.js
  src/store/mutations.js
Labels: frontend, debug, backport

#1271 Update Jest configuration for nextcloud/vue v8
  package-lock.json
  package.json
Labels: test, ci

#1272 Add appName to jest setup
  src/tests/jest.setup.js
Labels: test, ci

#1275 v4.0.4 rc1
  appinfo/info.xml
Labels: chore, release

#1165 Backport: Add user as workspace manager with workspace:create command, even if the workspace already exists
  lib/Commands/Create.php
  lib/Db/SpaceMapper.php
  lib/Space/SpaceManager.php
  tests/Unit/Space/SpaceManagerTest.php
Labels: backend, refactor, backport

#1159 Backport: Refactor SQL query handling to return early false for empty ConnectedGroups entities
  lib/Db/GroupFoldersGroupsMapper.php
Labels: backend, debug, backport

#1158 Backport: Using the tab indent style for PHP, CSS, JS and Vue in our code editor
  .editorconfig
Labels: debug, chore, backport

#1277 Make workspace available for Nextcloud 31
  appinfo/info.xml
Labels: chore

#1278 v4.0.4 rc2
  appinfo/info.xml
Labels: chore, release

#1280 Update import links for javascript dependencies
  src/AddUsersTabs.vue
  src/AlertRemoveGroup.vue
  src/ButtonUploadLocalFile.vue
  src/ButtonUploadShareFiles.vue
  src/GroupDetails.vue
  src/GroupMenuItem.vue
  src/Home.vue
  src/LeftSidebar.vue
  src/LoadingUsers.vue
  src/MultiSelectUsers.vue
  src/RemoveSpace.vue
  src/SelectConnectedGroups.vue
  src/SpaceDetails.vue
  src/SpaceMenuItem.vue
  src/SpaceTable.vue
  src/UserCard.vue
  src/UserTable.vue
  src/WorkspaceContent.vue
  src/components/Modals/EditWorkspace.vue
Labels: chore
