Repository arawa/workspace, pull requests merged in 2025-05, with the labels that each got.

#1279 Update nextcloud/dialog to 5.3.8
  package-lock.json
  package.json
  src/ButtonUploadShareFiles.vue
  src/main.js
Labels: dependencies, chore

#1282 Replace title with name in Nextcloud components
  src/LeftSidebar.vue
  src/SelectConnectedGroups.vue
  src/SpaceDetails.vue
  src/SpaceMenuItem.vue
Labels: frontend, refactor

#1284 Backport: Make workspace available for Nextcloud 31
  appinfo/info.xml
Labels: chore, backport

#1281 feat: database checker for workspace
  scripts/database_checker.php
Labels: feature, backend

#1285 Backport: Database checker for workspace
  scripts/database_checker.php
Labels: feature, backend, backport

#1289 v4.0.4 rc3
  appinfo/info.xml
Labels: chore, release

#1291 Update release to v4.1.0-rc5
  appinfo/info.xml
Labels: chore, release

#1273 fix: optimise use of count users from groups
  lib/Controller/WorkspaceController.php
  lib/Service/Group/GroupFormatter.php
Labels: debug, refactor

#1299 v4.0.4 rc4
  appinfo/info.xml
Labels: chore, release

#1300 Create middleware for ocs controller
  lib/AppInfo/Application.php
  lib/Attributes/GeneralManagerRequired.php
  lib/Attributes/WorkspaceManagerRequired.php
  lib/Middleware/GeneralManagerAccessMiddleware.php
  lib/Middleware/WorkspaceManagerAccessMiddleware.php
  lib/Service/SpaceService.php
Labels: feature, backend
