Repository arawa/workspace, pull requests merged in 2025-06, with the labels that each got.

#1312 Check existing space and id space with attributes
  lib/AppInfo/Application.php
  lib/Attributes/RequireExistingSpace.php
  lib/Attributes/SpaceIdNumber.php
  lib/Middleware/RequireExistingSpaceMiddleware.php
  lib/Middleware/SpaceIdNumberMiddleware.php
  lib/Middleware/WorkspaceManagerAccessMiddleware.php
Labels: feature, backend

#1306 Redesign after updating nextcloud/vue 8.x
  css/workspace-style.css
  src/AddUsersTabs.vue
  src/GroupDetails.vue
  src/LeftSidebar.vue
  src/MenuItemSelector.vue
  src/SpaceDetails.vue
Labels: frontend, redesign, refactor

#1303 Add connected group from "all workspace" list crash
  src/SelectConnectedGroups.vue
  src/SpaceDetails.vue
  src/SpaceMenuItem.vue
  src/store/actions.js
  src/store/mutations.js
Labels: frontend, debug

#1293 Change quota to bubble style
  src/SpaceDetails.vue
Labels: frontend, redesign

#1292 fix: #3874 GroupFolder changed getFolder
  lib/Helper/GroupfolderHelper.php
Labels: backend, debug

#1324 Bacport: Can't add connected group from workspaces list/1303/main
  src/SelectConnectedGroups.vue
  src/SpaceDetails.vue
  src/SpaceMenuItem.vue
  src/store/actions.js
  src/store/mutations.js
Labels: frontend, debug, backport

#1326 Backport: Update bootstrap config
  .github/workflows/php.yml
  composer.lock
  tests/bootstrap.php
Labels: backend, test, ci
