Repository arawa/workspace, pull requests merged in 2025-03, with the labels that each got.

#1195 Remove duplicate user requests when navigating to a workspace or refreshing it
  src/SpaceDetails.vue
  src/SpaceMenuItem.vue
Labels: frontend, debug

#1196 Backport: Remove duplicate user requests
  src/SpaceDetails.vue
  src/SpaceMenuItem.vue
Labels: frontend, debug, backport

#1197 Repair display name changes for workspace groups and subgroups with PostgreSQL
  lib/Db/GroupFoldersGroupsMapper.php
Labels: backend, debug

#1198 Backport: Repair display name changes for workspace groups and subgroups with PostgreSQL
  lib/Db/GroupFoldersGroupsMapper.php
Labels: backend, debug, backport

#1199 User groups are sorted by alphabetically
  src/UserTable.vue
Labels: frontend, debug

#1200 Backport: Sort groups in user table in user table
  src/UserTable.vue
Labels: frontend, debug, backport

#1201 Release: v4.0.2 rc3
  appinfo/info.xml
Labels: chore, release

#1204 Keep the focus on the user search input
  src/MultiSelectUsers.vue
Labels: frontend, debug

#1205 backport: Keep the focus on the user search input
  src/MultiSelectUsers.vue
Labels: frontend, debug

#1206 The added group icon is compatible with dark mode
  css/workspace-style.css
  img/added_group_white.svg
Labels: frontend, debug

#1207 Add upper case letters to the words ‘Workspaces’ in the French translation
  l10n/fr.js
  l10n/fr.json
Labels: translating

#1210 Backport: Add upper case letters to the words ‘Workspaces’ in the French translation
  l10n/fr.js
  l10n/fr.json
Labels: translating

#1211 Release v4.0.2 rc4
  appinfo/info.xml
Labels: chore, release

#1213 Release v4.0.2
  CHANGELOG.md
  appinfo/info.xml
Labels: documentation, release

#1216 Harmonize user select input with the added group select input
  src/MultiSelectUsers.vue
Labels: frontend, refactor

#1219 Allow adding groups that contain slashes
  appinfo/routes.php
  src/store/actions.js
Labels: backend, frontend, api, debug

#1220 fix: don't show old legacy local groups as connected groups
  lib/Controller/ConnectedGroupController.php
  lib/Controller/GroupController.php
  lib/Controller/WorkspaceController.php
  lib/Service/Group/ConnectedGroupsService.php
  lib/Service/Group/GroupFormatter.php
  lib/Service/Group/GroupsWorkspace.php
  lib/Service/UserService.php
  lib/Space/SpaceManager.php
  src/UserTable.vue
Labels: backend, frontend, debug

#1222 Backport: connected groups with slashs
  appinfo/routes.php
  src/store/actions.js
Labels: backend, frontend, api, debug, backport

#1217 Backport: Harmonize user select input with the added group select input
  src/MultiSelectUsers.vue
Labels: frontend, refactor, backport

#1209 Backport: The added group icon is compatible with dark mode
  css/workspace-style.css
  img/added_group_white.svg
Labels: frontend, debug

#1208 Backport : Determine if a user belongs to an added group
  lib/Service/Group/ConnectedGroupsService.php
Labels: backend, debug, backport

#1224 Backport: old subgroups in added groups section prop 2
  lib/Controller/ConnectedGroupController.php
  lib/Controller/GroupController.php
  lib/Controller/WorkspaceController.php
  lib/Service/Group/ConnectedGroupsService.php
  lib/Service/Group/GroupFormatter.php
  lib/Service/Group/GroupsWorkspace.php
  lib/Service/UserService.php
  lib/Space/SpaceManager.php
  src/UserTable.vue
Labels: backend, frontend, debug, backport

#1203 Optimize user state for users in added groups
  lib/Controller/ConnectedGroupController.php
  lib/Db/GroupFoldersGroupsMapper.php
  lib/Service/Group/ConnectedGroupsService.php
  lib/Service/User/UserFormatter.php
  lib/Service/UserService.php
  lib/Users/UserFormatter.php
Labels: backend, refactor

#1221 Backport: count bubble workspace
  appinfo/routes.php
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  lib/Controller/WorkspaceController.php
  lib/Db/SpaceMapper.php
  src/LeftSidebar.vue
  src/SpaceDetails.vue
  src/services/spaceService.js
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
Labels: feature, backend, frontend, backport

#1226 Release v4.1.0
  appinfo/info.xml
Labels: chore, release
