Repository arawa/workspace, pull requests merged in 2025-10, with the labels that each got.

#1301 Create a duplicate group with a specific id
  l10n/en.js
  l10n/fr.js
  l10n/fr.json
  src/services/Groups/functions.js
  src/store/actions.js
Labels: frontend, debug

#1408 v4.1.0-rc12
  appinfo/info.xml
Labels: chore, release

#1409 Add attribute to forbid special characters
  lib/AppInfo/Application.php
  lib/Attributes/NoSpecialChar.php
  lib/Controller/WorkspaceApiOcsController.php
  lib/Middleware/NoSpecialCharMiddleware.php
  lib/Space/SpaceManager.php
Labels: feature, backend, api

#1410 v4.1.0-rc13
  appinfo/info.xml
Labels: chore, release

#1412 Revert "Add attribute to forbid special characters"
  lib/AppInfo/Application.php
  lib/Attributes/NoSpecialChar.php
  lib/Controller/WorkspaceApiOcsController.php
  lib/Middleware/NoSpecialCharMiddleware.php
  lib/Space/SpaceManager.php
Labels: backend, api, revert
