Repository arawa/workspace, pull requests merged in 2025-08, with the labels that each got.

#1367 v4.1.0-dev3
  appinfo/info.xml
Labels: api, chore, release

#1370 Remove files from groupfolders on the web server
  lib/Exceptions/MountProviderFunctionException.php
  lib/Helper/MountProviderHelper.php
  lib/Space/SpaceManager.php
  scripts/database_checker.php
  tests/Unit/Space/SpaceManagerTest.php
Labels: backend, debug

#1373 Enable checkbox when adding a user who's not a WM
  src/AddUsersTabs.vue
  src/UserCard.vue
Labels: frontend, debug

#1374 Take added groups into account in ACLs
  lib/AppInfo/Application.php
Labels: backend, debug

#1375 v4.1.0-rc8
  appinfo/info.xml
Labels: chore, release
